spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipedb
    username: root
    password: TejaDivvi$123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
